import type { MilestoneTemplate } from "../types/checklist";

export const MILESTONE_TEMPLATES: MilestoneTemplate[] = [
  // ═══════════════════════════════════════════════════════════════
  // PREGNANCY — offset_weeks relative to due_date (negative = before due date)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "first_prenatal",
    title: "Schedule first prenatal appointment",
    description: "Confirm pregnancy and establish care with your OB-GYN or midwife.",
    category: "pregnancy",
    offset_weeks: -32,
    offset_reference: "due_date",
    icon: "Stethoscope",
  },
  {
    key: "prenatal_vitamins",
    title: "Start prenatal vitamins",
    description: "Begin taking folic acid and prenatal vitamins daily.",
    category: "pregnancy",
    offset_weeks: -32,
    offset_reference: "due_date",
    icon: "Pill",
  },
  {
    key: "announce_pregnancy",
    title: "Share the news (if ready)",
    description: "Many families share after the first trimester, but there\u2019s no wrong time.",
    category: "pregnancy",
    offset_weeks: -26,
    offset_reference: "due_date",
    icon: "Heart",
  },
  {
    key: "anatomy_scan",
    title: "Anatomy scan (20-week ultrasound)",
    description: "Detailed ultrasound to check baby\u2019s development and anatomy.",
    category: "pregnancy",
    offset_weeks: -20,
    offset_reference: "due_date",
    icon: "Scan",
  },
  {
    key: "start_registry",
    title: "Start baby registry",
    description: "Begin researching and registering for essentials like a crib, car seat, and stroller.",
    category: "pregnancy",
    offset_weeks: -18,
    offset_reference: "due_date",
    icon: "Gift",
  },
  {
    key: "glucose_test",
    title: "Glucose tolerance test",
    description: "Screening for gestational diabetes, typically between 24\u201328 weeks.",
    category: "pregnancy",
    offset_weeks: -14,
    offset_reference: "due_date",
    icon: "TestTube",
  },
  {
    key: "childbirth_class",
    title: "Sign up for childbirth class",
    description: "Consider a class covering labor, delivery, and newborn care basics.",
    category: "pregnancy",
    offset_weeks: -14,
    offset_reference: "due_date",
    icon: "GraduationCap",
  },
  {
    key: "nursery_setup",
    title: "Set up nursery",
    description: "Assemble crib, organize clothes, and prepare the baby\u2019s space.",
    category: "pregnancy",
    offset_weeks: -10,
    offset_reference: "due_date",
    icon: "Home",
  },
  {
    key: "choose_pediatrician",
    title: "Choose a pediatrician",
    description: "Interview and select a pediatrician before baby arrives.",
    category: "pregnancy",
    offset_weeks: -8,
    offset_reference: "due_date",
    icon: "UserCheck",
  },
  {
    key: "hospital_bag",
    title: "Pack hospital bag",
    description: "Prepare essentials for labor, delivery, and your hospital stay.",
    category: "pregnancy",
    offset_weeks: -6,
    offset_reference: "due_date",
    icon: "Luggage",
  },
  {
    key: "install_car_seat",
    title: "Install infant car seat",
    description: "Install and have it inspected at a local fire station or certified technician.",
    category: "pregnancy",
    offset_weeks: -5,
    offset_reference: "due_date",
    icon: "Car",
  },
  {
    key: "birth_plan",
    title: "Finalize birth plan",
    description: "Discuss your preferences for labor and delivery with your care team.",
    category: "pregnancy",
    offset_weeks: -4,
    offset_reference: "due_date",
    icon: "ClipboardList",
  },
  {
    key: "prep_meals",
    title: "Prepare freezer meals",
    description: "Stock up on easy meals for the first weeks after baby arrives.",
    category: "pregnancy",
    offset_weeks: -4,
    offset_reference: "due_date",
    icon: "UtensilsCrossed",
  },
  {
    key: "tdap_vaccine",
    title: "Tdap vaccine (whooping cough)",
    description: "Recommended between 27\u201336 weeks to pass antibodies to baby.",
    category: "pregnancy",
    offset_weeks: -8,
    offset_reference: "due_date",
    icon: "Syringe",
  },

  // ═══════════════════════════════════════════════════════════════
  // POSTPARTUM — offset_weeks relative to birth
  // ═══════════════════════════════════════════════════════════════
  {
    key: "newborn_checkup",
    title: "Newborn checkup (3\u20135 days)",
    description: "First pediatrician visit to check weight, feeding, and jaundice.",
    category: "postpartum",
    offset_weeks: 1,
    offset_reference: "birth",
    icon: "Baby",
  },
  {
    key: "birth_certificate",
    title: "File birth certificate",
    description: "Submit paperwork for birth certificate and Social Security number.",
    category: "postpartum",
    offset_weeks: 2,
    offset_reference: "birth",
    icon: "FileText",
  },
  {
    key: "add_to_insurance",
    title: "Add baby to health insurance",
    description: "Most plans require adding a newborn within 30 days of birth.",
    category: "postpartum",
    offset_weeks: 2,
    offset_reference: "birth",
    icon: "Shield",
  },
  {
    key: "postpartum_checkup",
    title: "Schedule postpartum checkup",
    description: "Follow up with your OB-GYN or midwife around 6 weeks postpartum.",
    category: "postpartum",
    offset_weeks: 4,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "two_month_vaccines",
    title: "2-month well visit and vaccines",
    description: "First round of immunizations and developmental checkup.",
    category: "postpartum",
    offset_weeks: 8,
    offset_reference: "birth",
    icon: "Syringe",
  },
  {
    key: "four_month_vaccines",
    title: "4-month well visit and vaccines",
    description: "Second round of immunizations and growth check.",
    category: "postpartum",
    offset_weeks: 17,
    offset_reference: "birth",
    icon: "Syringe",
  },
  {
    key: "start_solids",
    title: "Introduce solid foods",
    description: "Most babies are ready around 6 months. Watch for signs of readiness.",
    category: "postpartum",
    offset_weeks: 26,
    offset_reference: "birth",
    icon: "Apple",
  },
  {
    key: "six_month_vaccines",
    title: "6-month well visit and vaccines",
    description: "Third round of immunizations and developmental screening.",
    category: "postpartum",
    offset_weeks: 26,
    offset_reference: "birth",
    icon: "Syringe",
  },
  {
    key: "babyproof_home",
    title: "Baby-proof the house",
    description: "Cover outlets, secure furniture, install gates as baby starts to move.",
    category: "postpartum",
    offset_weeks: 26,
    offset_reference: "birth",
    icon: "ShieldCheck",
  },

  // ═══════════════════════════════════════════════════════════════
  // DEVELOPMENT — offset_weeks relative to birth
  // ═══════════════════════════════════════════════════════════════
  {
    key: "nine_month_visit",
    title: "9-month well visit",
    description: "Developmental screening and growth check.",
    category: "development",
    offset_weeks: 39,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "first_birthday",
    title: "Plan first birthday",
    description: "Celebrate this milestone! Schedule 12-month checkup too.",
    category: "development",
    offset_weeks: 52,
    offset_reference: "birth",
    icon: "Cake",
  },
  {
    key: "twelve_month_visit",
    title: "12-month well visit and vaccines",
    description: "MMR, varicella, and hepatitis A vaccines. Lead screening.",
    category: "development",
    offset_weeks: 52,
    offset_reference: "birth",
    icon: "Syringe",
  },
  {
    key: "transition_to_milk",
    title: "Transition to whole milk",
    description: "Around 12 months, transition from formula or breast milk to whole cow\u2019s milk.",
    category: "development",
    offset_weeks: 52,
    offset_reference: "birth",
    icon: "Cup",
  },
  {
    key: "fifteen_month_visit",
    title: "15-month well visit",
    description: "Booster vaccines and developmental check.",
    category: "development",
    offset_weeks: 65,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "eighteen_month_visit",
    title: "18-month well visit",
    description: "Autism screening (M-CHAT) and hepatitis A vaccine.",
    category: "development",
    offset_weeks: 78,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "two_year_visit",
    title: "2-year well visit",
    description: "Developmental and behavioral screening. Height, weight, BMI check.",
    category: "development",
    offset_weeks: 104,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "potty_training",
    title: "Watch for potty training readiness",
    description: "Most children show signs of readiness between 18\u201336 months.",
    category: "development",
    offset_weeks: 104,
    offset_reference: "birth",
    icon: "Star",
  },
  {
    key: "three_year_visit",
    title: "3-year well visit",
    description: "Vision screening, developmental assessment, and growth check.",
    category: "development",
    offset_weeks: 156,
    offset_reference: "birth",
    icon: "Stethoscope",
  },
  {
    key: "preschool_research",
    title: "Research preschool options",
    description: "Tour local preschools and understand enrollment timelines.",
    category: "development",
    offset_weeks: 130,
    offset_reference: "birth",
    icon: "School",
  },
  {
    key: "four_year_visit",
    title: "4-year well visit and vaccines",
    description: "Pre-kindergarten vaccines (DTaP, IPV, MMR, varicella boosters).",
    category: "development",
    offset_weeks: 208,
    offset_reference: "birth",
    icon: "Syringe",
  },
];
